version: "3.9"

services:
  db:
    image: postgres:16
    container_name: toilet_tracker_db
    restart: always
    environment:
      POSTGRES_DB: toilet_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: toilet_tracker_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  backend:
    build: ./backend
    container_name: toilet_tracker_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/toilet_tracker
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

volumes:
  postgres_data: